### ISSUE TITLE
Full test of tutorial and report issues

### ISSUE THREAD

**Issue by max-elia** [eclipsesource/glsp-tutorial#4]

**Comment by max-elia** [comment]
* Extra Step for setup (if in Gitpod -> already done, skip)
* A service is available port 3000 -> maybe notice to refresh
* Java syntax highlighting broken (Configuration Dockerfile?)
* Kill ports at first build
* Step3 size to 20,20 in normal description
* Build button on last step
* Extend descriptions for some exercises

**Comment by JonasHelming** [comment]
@max-elia : Could you recheck the issues above if anything is still relevant and if so created dedicated issues and close this one please.
